# Generated by Django 4.2.9 on 2024-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
